name: Prompt Debugger MacOS
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        #platform: [ macos-latest,macos-13,macos-11 ]
        platform: [ macos-13 ]
        arch: [ x86_64 ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.platform }}${{ matrix.arch }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.0'
          architecture: "x64"
          cache: 'pip'
      - name: 安装项目依赖包
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "/usr/bin" >> $GITHUB_PATH
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build and Package for ${{ matrix.platform }}${{ matrix.arch }}
        env:
          PATH: ${{ matrix.path }} # 设置环境变量
        run: |
          #pyinstaller --noconfirm --onefile --windowed --icon logo.png  -n="prompt debugger"  main.py
          pyinstaller --noconfirm --onefile --noconsole -w --windowed -n="prompt debugger"  main.py
      # 上传生成的二进制文件到 artifacts 存储
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}-${{ matrix.arch }}-binary
          path: dist/
