name: Prompt Debugger MacOS
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        #platform: [ macos-latest,macos-13,macos-11 ]
        platform: [ macos-latest ]
        arch: [ x86_64,arm64 ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: 启动 Python ${{ matrix.platform }}${{ matrix.arch }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.7'
          architecture: "x64"
          cache: 'pip'
      - name: 安装项目依赖包
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "/usr/bin" >> $GITHUB_PATH
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build and Package for ${{ matrix.platform }}${{ matrix.arch }}
        run: |
          pyinstaller --noconfirm -w -F main.py -n="prompt_debugger" -i logo.png --clean

      - name: 调整目录权限
        run: |
            echo "/usr/bin" >> $GITHUB_PATH
            ls $HOME/work/prompt_debugger/prompt_debugger/dist
            chmod -R +x $HOME/work/prompt_debugger/prompt_debugger/dist/prompt_debugger.app/*

      # 上传生成的二进制文件到 artifacts 存储
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}-${{ matrix.arch }}-binary
          path: dist/
