name: Multi-platform Build and Packaging
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ macos-latest ]
        arch: [ x86_64 ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.platform }}${{ matrix.arch }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.0'
          architecture: "x64"
          cache: 'pip'
      - name: Verify 'arch' command
        run: arch
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install 'archer' with Homebrew
        run: brew install archer

      - name: Install dependencies packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Build and Package for ${{ matrix.platform }}${{ matrix.arch }}
        env:
          PATH: ${{ matrix.path }} # 设置环境变量
        run: |
          pyinstaller --noconfirm -w -F main.py -n="prompt debugger" -i logo.png --clean --target-architecture x86_64
      # 上传生成的二进制文件到 artifacts 存储
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}-${{ matrix.arch }}-binary
          path: dist/
