name: Multi-platform Build and Packaging
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ windows-latest ]
        arch: [ x64 ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.os }}${{ matrix.architecture }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.0'
          architecture: "x64"
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --user -r requirements.txt
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          # 添加其他依赖安装命令
      - name: Build and Package for ${{ matrix.platform }}${{ matrix.arch }}
        env:
          PATH: ${{ matrix.path }} # 设置环境变量
        run: |
          pyinstaller --noconfirm -w -F main.py -n="prompt debugger" -i logo.png --clean
      # 上传生成的二进制文件到 artifacts 存储
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}-${{ matrix.arch }}-binary
          path: dist/
